version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cyberlens-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cyberlens
      POSTGRES_USER: cyberlens_user
      POSTGRES_PASSWORD: cyberlens_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - cyberlens-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: cyberlens-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cyberlens-network

  # Backend API (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cyberlens-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://cyberlens_user:cyberlens_password@postgres:5432/cyberlens
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - cyberlens-network
    command: npm run start:dev

  # Prisma Studio (Database GUI)
  prisma-studio:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cyberlens-prisma-studio
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://cyberlens_user:cyberlens_password@postgres:5432/cyberlens
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - cyberlens-network
    command: npx prisma studio --port 5555 --hostname 0.0.0.0

  # pgAdmin (PostgreSQL Administration)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cyberlens-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cyberlens.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - cyberlens-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  cyberlens-network:
    driver: bridge